import type { Case, Contact } from "./types"

const USE_RICH_MOCK_DATA = true // Set to false to revert to minimal data

export const mockContacts: Contact[] = [
  // Hotel Staff
  {
    id: "hotel-1",
    name: "Maria Santos",
    role: "Hotel Manager",
    category: "Hotel Staff",
    status: "online",
    avatar: "MS",
    phone: "+1-555-0123",
    location: "Grand Resort",
    isFavorite: true,
    lastSeen: "Just now",
  },
  {
    id: "hotel-2",
    name: "James Wilson",
    role: "Front Desk",
    category: "Hotel Staff",
    status: "online",
    avatar: "JW",
    phone: "+1-555-0124",
    location: "Grand Resort",
    isFavorite: false,
    lastSeen: "2 minutes ago",
  },
  // EMS Personnel
  {
    id: "ems-1",
    name: "Dr. Carlos Rodriguez",
    role: "Paramedic",
    category: "EMS Personnel",
    status: "busy",
    avatar: "CR",
    phone: "+52-998-123-4567",
    location: "Emergency Services",
    isFavorite: true,
    lastSeen: "5 minutes ago",
  },
  {
    id: "ems-2",
    name: "Ana Gutierrez",
    role: "EMT",
    category: "EMS Personnel",
    status: "offline",
    avatar: "AG",
    phone: "+52-998-123-4568",
    location: "Emergency Services",
    isFavorite: false,
    lastSeen: "2 hours ago",
  },
  // Medical Clinics
  {
    id: "clinic-1",
    name: "Dr. Sarah Chen",
    role: "Emergency Physician",
    category: "Medical Clinics",
    status: "online",
    avatar: "SC",
    phone: "+52-998-987-6543",
    location: "Medical Center",
    isFavorite: true,
    lastSeen: "Just now",
  },
  {
    id: "clinic-2",
    name: "Dr. Miguel Torres",
    role: "General Practitioner",
    category: "Medical Clinics",
    status: "away",
    avatar: "MT",
    phone: "+52-998-987-6544",
    location: "Plaza Clinic",
    isFavorite: false,
    lastSeen: "15 minutes ago",
  },
  // Tour Operators
  {
    id: "tour-1",
    name: "Roberto Mendez",
    role: "Tour Guide",
    category: "Tour Operators",
    status: "online",
    avatar: "RM",
    phone: "+52-998-555-7890",
    location: "Adventure Tours",
    isFavorite: false,
    lastSeen: "1 minute ago",
  },
  {
    id: "translator-1",
    name: "Lisa Park",
    role: "Medical Translator",
    category: "Support Services",
    status: "online",
    avatar: "LP",
    phone: "+52-998-555-7891",
    location: "Translation Services",
    isFavorite: true,
    lastSeen: "Just now",
  },
]

const richMockCases: Case[] = [
  {
    id: "CASE-001",
    title: "Food Poisoning - Hotel Guest",
    timestamp: "8/25/2025, 6:14:47 PM",
    messages: [
      {
        id: "msg-001-1",
        text: "Guest in room 305 reporting severe nausea and vomiting after dinner. Need immediate medical assistance.",
        sender: "hotel-1",
        timestamp: "8/25/2025, 6:14:47 PM",
        status: "read",
        reactions: [{ emoji: "👍", users: ["ems-1"] }],
      },
      {
        id: "msg-001-2",
        text: "On my way. ETA 5 minutes. What did they eat?",
        sender: "ems-1",
        timestamp: "8/25/2025, 6:16:12 PM",
        status: "read",
      },
      {
        id: "msg-001-3",
        text: "Seafood buffet around 5 PM. Guest is 45-year-old male, no known allergies.",
        sender: "hotel-1",
        timestamp: "8/25/2025, 6:17:30 PM",
        status: "read",
        attachments: [
          {
            id: "att-001",
            name: "guest_info.pdf",
            type: "application/pdf",
            size: 245760,
            url: "/placeholder-document.pdf",
          },
        ],
      },
      {
        id: "msg-001-4",
        text: "📍 Current location: Grand Resort, Room 305",
        sender: "hotel-1",
        timestamp: "8/25/2025, 6:18:00 PM",
        status: "delivered",
        location: {
          latitude: 21.1619,
          longitude: -86.8515,
          address: "Grand Resort, Room 305, Cancun",
        },
      },
      {
        id: "msg-001-5",
        text: "🎤 Voice message (0:45)",
        sender: "ems-1",
        timestamp: "8/25/2025, 6:19:30 PM",
        status: "read",
        voiceMessage: {
          duration: 45,
          url: "/placeholder-audio.mp3",
        },
      },
      {
        id: "msg-001-6",
        text: "Patient vitals stable. Administering IV fluids.",
        sender: "ems-1",
        timestamp: "8/25/2025, 6:25:00 PM",
        status: "failed",
        reactions: [],
      },
      {
        id: "msg-001-7",
        text: "Patient vitals stable. Administering IV fluids.",
        sender: "ems-1",
        timestamp: "8/25/2025, 6:25:30 PM",
        status: "read",
        reactions: [{ emoji: "❤️", users: ["hotel-1"] }],
      },
    ],
    status: "active",
    unreadCount: 2,
    participants: ["hotel-1", "ems-1"],
    createdBy: "tourist-001",
    priority: "high",
  },
  {
    id: "CASE-002",
    title: "Tour Accident - Ankle Injury",
    timestamp: "8/25/2025, 4:29:47 PM",
    messages: [
      {
        id: "msg-002-1",
        text: "Tourist slipped on wet rocks during cenote tour. Possible ankle fracture.",
        sender: "tour-1",
        timestamp: "8/25/2025, 4:29:47 PM",
        status: "read",
      },
      {
        id: "msg-002-2",
        text: "Can you bring them to the clinic? I have X-ray available.",
        sender: "clinic-1",
        timestamp: "8/25/2025, 4:32:15 PM",
        status: "read",
      },
      {
        id: "msg-002-3",
        text: "Patient is stable, applying ice pack. Will transport in 10 minutes.",
        sender: "tour-1",
        timestamp: "8/25/2025, 4:35:20 PM",
        status: "read",
        attachments: [
          {
            id: "att-002",
            name: "injury_photo.jpg",
            type: "image/jpeg",
            size: 1024000,
            url: "/placeholder.svg?height=300&width=400",
          },
        ],
      },
      {
        id: "msg-002-4",
        text: "Sending patient insurance information and passport copy.",
        sender: "tour-1",
        timestamp: "8/25/2025, 4:40:00 PM",
        status: "delivered",
        attachments: [
          {
            id: "att-002-2",
            name: "insurance_card.jpg",
            type: "image/jpeg",
            size: 512000,
            url: "/placeholder.svg?height=200&width=320",
          },
          {
            id: "att-002-3",
            name: "passport_copy.pdf",
            type: "application/pdf",
            size: 1024000,
            url: "/placeholder-document.pdf",
          },
        ],
      },
      {
        id: "msg-002-5",
        text: "📍 Cenote Dos Ojos - Emergency exit point",
        sender: "tour-1",
        timestamp: "8/25/2025, 4:42:00 PM",
        status: "sent",
        location: {
          latitude: 20.2285,
          longitude: -87.4256,
          address: "Cenote Dos Ojos, Quintana Roo, Mexico",
        },
      },
    ],
    status: "active",
    unreadCount: 1,
    participants: ["tour-1", "clinic-1"],
    createdBy: "tourist-001",
    priority: "medium",
  },
  {
    id: "CASE-003",
    title: "Medical Emergency - Allergic Reaction",
    timestamp: "8/24/2025, 2:15:30 PM",
    messages: [
      {
        id: "msg-003-1",
        text: "URGENT: Guest having severe allergic reaction to shellfish. Administered EpiPen.",
        sender: "ems-1",
        timestamp: "8/24/2025, 2:15:30 PM",
        status: "read",
        reactions: [{ emoji: "🚨", users: ["clinic-2"] }],
      },
      {
        id: "msg-003-2",
        text: "Patient stabilized. Transported to hospital for observation. Case closed.",
        sender: "clinic-2",
        timestamp: "8/24/2025, 3:45:00 PM",
        status: "read",
      },
      {
        id: "msg-003-3",
        text: "Thank you for the quick response. Patient discharged and doing well.",
        sender: "ems-1",
        timestamp: "8/24/2025, 8:30:00 PM",
        status: "read",
        reactions: [
          { emoji: "❤️", users: ["clinic-2"] },
          { emoji: "👍", users: ["hotel-1"] },
        ],
      },
    ],
    status: "completed",
    unreadCount: 0,
    participants: ["ems-1", "clinic-2"],
    createdBy: "tourist-001",
    priority: "urgent",
  },
  {
    id: "CASE-004",
    title: "Heart Attack - Pool Area",
    timestamp: "8/25/2025, 8:45:22 PM",
    messages: [
      {
        id: "msg-004-1",
        text: "EMERGENCY: 60-year-old male collapsed by pool. CPR in progress.",
        sender: "hotel-2",
        timestamp: "8/25/2025, 8:45:22 PM",
        status: "read",
      },
      {
        id: "msg-004-2",
        text: "Ambulance dispatched. Continue CPR. ETA 3 minutes.",
        sender: "ems-1",
        timestamp: "8/25/2025, 8:46:00 PM",
        status: "read",
      },
      {
        id: "msg-004-3",
        text: "📍 Pool deck, north side of resort",
        sender: "hotel-2",
        timestamp: "8/25/2025, 8:46:30 PM",
        status: "delivered",
        location: {
          latitude: 21.1625,
          longitude: -86.852,
          address: "Grand Resort Pool Deck, Cancun",
        },
      },
      {
        id: "msg-004-4",
        text: "🎤 Voice message (1:20) - Patient update",
        sender: "ems-1",
        timestamp: "8/25/2025, 8:50:00 PM",
        status: "delivered",
        voiceMessage: {
          duration: 80,
          url: "/placeholder-audio.mp3",
        },
        reactions: [{ emoji: "🙏", users: ["hotel-2"] }],
      },
      {
        id: "msg-004-5",
        text: "Pulse restored. Patient conscious and responsive. Great work everyone!",
        sender: "clinic-1",
        timestamp: "8/25/2025, 8:55:00 PM",
        status: "sent",
        reactions: [
          { emoji: "🎉", users: ["hotel-2", "ems-1"] },
          { emoji: "❤️", users: ["hotel-2"] },
        ],
      },
    ],
    status: "active",
    unreadCount: 3,
    participants: ["hotel-2", "ems-1", "clinic-1"],
    createdBy: "tourist-002",
    priority: "urgent",
  },
  {
    id: "CASE-005",
    title: "Minor Cut - Kitchen Accident",
    timestamp: "8/25/2025, 1:20:15 PM",
    messages: [
      {
        id: "msg-005-1",
        text: "Staff member cut finger while preparing lunch. Need basic first aid.",
        sender: "hotel-1",
        timestamp: "8/25/2025, 1:20:15 PM",
        status: "read",
      },
      {
        id: "msg-005-2",
        text: "Clean wound, apply pressure, and bandage. Monitor for signs of infection.",
        sender: "clinic-2",
        timestamp: "8/25/2025, 1:22:30 PM",
        status: "read",
      },
      {
        id: "msg-005-3",
        text: "Wound cleaned and bandaged. Staff member back to work. Thanks!",
        sender: "hotel-1",
        timestamp: "8/25/2025, 1:35:00 PM",
        status: "read",
        reactions: [{ emoji: "👍", users: ["clinic-2"] }],
      },
    ],
    status: "completed",
    unreadCount: 0,
    participants: ["hotel-1", "clinic-2"],
    createdBy: "hotel-1",
    priority: "low",
  },
  {
    id: "CASE-006",
    title: "Medication Request - Diabetes",
    timestamp: "8/25/2025, 11:30:00 AM",
    messages: [
      {
        id: "msg-006-1",
        text: "Guest forgot insulin medication. Need prescription refill urgently.",
        sender: "hotel-1",
        timestamp: "8/25/2025, 11:30:00 AM",
        status: "read",
      },
      {
        id: "msg-006-2",
        text: "I can help. Need to see their medical records and ID.",
        sender: "clinic-1",
        timestamp: "8/25/2025, 11:32:00 AM",
        status: "read",
      },
      {
        id: "msg-006-3",
        text: "Guest will come to clinic at 2 PM with documents.",
        sender: "hotel-1",
        timestamp: "8/25/2025, 11:35:00 AM",
        status: "read",
        attachments: [
          {
            id: "att-006",
            name: "insurance_card.jpg",
            type: "image/jpeg",
            size: 512000,
            url: "/placeholder.svg?height=200&width=320",
          },
        ],
      },
      {
        id: "msg-006-4",
        text: "Prescription filled. Guest has 7-day supply. Case resolved.",
        sender: "clinic-1",
        timestamp: "8/25/2025, 2:45:00 PM",
        status: "read",
      },
      {
        id: "msg-006-5",
        text: "Follow-up: How is the patient feeling today?",
        sender: "clinic-1",
        timestamp: "8/26/2025, 9:00:00 AM",
        status: "failed",
      },
      {
        id: "msg-006-6",
        text: "Follow-up: How is the patient feeling today?",
        sender: "clinic-1",
        timestamp: "8/26/2025, 9:01:00 AM",
        status: "delivered",
      },
    ],
    status: "completed",
    unreadCount: 0,
    participants: ["hotel-1", "clinic-1"],
    createdBy: "tourist-003",
    priority: "medium",
  },
  {
    id: "CASE-007",
    title: "Language Barrier - Medical Consultation",
    timestamp: "8/23/2025, 3:15:00 PM",
    messages: [
      {
        id: "msg-007-1",
        text: "Chinese tourist needs medical help but language barrier. Requesting translator.",
        sender: "hotel-1",
        timestamp: "8/23/2025, 3:15:00 PM",
        status: "read",
      },
      {
        id: "msg-007-2",
        text: "I'm available for Mandarin translation. What's the medical issue?",
        sender: "translator-1",
        timestamp: "8/23/2025, 3:18:00 PM",
        status: "read",
      },
      {
        id: "msg-007-3",
        text: "🎤 Voice message (2:30) - Patient symptoms in Mandarin",
        sender: "translator-1",
        timestamp: "8/23/2025, 3:25:00 PM",
        status: "read",
        voiceMessage: {
          duration: 150,
          url: "/placeholder-audio.mp3",
        },
      },
      {
        id: "msg-007-4",
        text: "Patient reports chest pain and shortness of breath. Started 2 hours ago.",
        sender: "translator-1",
        timestamp: "8/23/2025, 3:27:00 PM",
        status: "read",
        reactions: [{ emoji: "🚨", users: ["clinic-1"] }],
      },
      {
        id: "msg-007-5",
        text: "This needs immediate attention. Bringing patient to clinic now.",
        sender: "clinic-1",
        timestamp: "8/23/2025, 3:30:00 PM",
        status: "read",
      },
      {
        id: "msg-007-6",
        text: "📍 Medical Center - Emergency entrance",
        sender: "clinic-1",
        timestamp: "8/23/2025, 3:32:00 PM",
        status: "read",
        location: {
          latitude: 21.158,
          longitude: -86.8473,
          address: "Medical Center, Emergency Entrance, Cancun",
        },
      },
      {
        id: "msg-007-7",
        text: "Patient stable after EKG. Minor anxiety attack, not cardiac. Discharged with instructions.",
        sender: "clinic-1",
        timestamp: "8/23/2025, 5:45:00 PM",
        status: "read",
        reactions: [
          { emoji: "😌", users: ["translator-1", "hotel-1"] },
          { emoji: "👍", users: ["hotel-1"] },
        ],
      },
    ],
    status: "completed",
    unreadCount: 0,
    participants: ["hotel-1", "translator-1", "clinic-1"],
    createdBy: "tourist-004",
    priority: "high",
  },
]

const minimalMockCases: Case[] = [
  {
    id: "CASE-001",
    title: "Food Poisoning - Hotel Guest",
    timestamp: "8/25/2025, 6:14:47 PM",
    messages: [],
    status: "active",
    unreadCount: 2,
    participants: ["hotel-1", "ems-1"],
    createdBy: "tourist-001",
  },
  {
    id: "CASE-002",
    title: "Tour Accident - Ankle Injury",
    timestamp: "8/25/2025, 4:29:47 PM",
    messages: [],
    status: "active",
    unreadCount: 1,
    participants: ["tour-1", "clinic-1"],
    createdBy: "tourist-001",
  },
  {
    id: "CASE-003",
    title: "Medical Emergency - Allergic Reaction",
    timestamp: "8/24/2025, 2:15:30 PM",
    messages: [],
    status: "completed",
    unreadCount: 0,
    participants: ["ems-1", "clinic-2"],
    createdBy: "tourist-001",
  },
]

export const mockCases: Case[] = USE_RICH_MOCK_DATA ? richMockCases : minimalMockCases
